apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server
spec:
  hostNetwork: true
  nodeSelector:
    kubernetes.io/hostname: ip-172-31-122-231.ec2.internal
  containers:
  - name: app
    image: ubuntu:latest
    command: ["/bin/bash"]
    args: ["-c", "apt update && \
                  apt install iproute2 iperf3 -y && \
                  ip r && for a in {172.31.122.231,172.31.117.195,172.31.99.203,172.31.124.218}; do for i in {5024..5033}; do echo $a:$i; iperf3 -s -p $i -B $a -V > /tmp/output.$a-$i.log & done; done && sleep 13600"]