apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 2.4Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - noatime
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-07bd4be9706160b42
    volumeAttributes:
      dnsname: fs-07bd4be9706160b42.fsx.us-east-1.amazonaws.com
      mountname: vdtrzbev
