apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 2.4Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - noatime
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0012c4cdfa036615a
    volumeAttributes:
      dnsname: fs-0012c4cdfa036615a.fsx.eu-west-1.amazonaws.com
      mountname: wcyvtbmv
